[project]
name = "mlops-course"
version = "0.1.0"
description = "MLOps course exercises"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
  "numpy",
]

[dependency-groups]
dev = [
  "pytest",
  "ruff",
  "black",
  "pre-commit",
]


